apiVersion: v1
kind: Pod
metadata:
  name: cpu-stress-pod
spec:
  containers:
  - name: cpu-stress
    image: vish/stress
    resources:
      limits:
        cpu: "1"
      requests:
        cpu: "0.2"
    args:
    - -cpus
    - "2"
